Feature/#1 게시물 Entity생성
prgrms-web-devcourse/Team-Moongsal-Travel.zip-BE pull request #4
Opened 2023-02-19 17:56 UTC by yewon9609

✅주영님과 함께 협업하여 구현하였습니다!

## 개발 내용 한줄 요약
Travelogue, SubTravelgue Entity 생성

## 개발 세부 사항
- Travelogue Entity생성
- Address 값객체 생성
- Period 값객체 생성
- Transportation Enum 생성
- SubTravelogue Entity 생성
- Image Entity 생성

❗️ Image Entity같은 경우 나중에 수정할 것을 고려하여 값타입 컬렉션이 아닌 Entity로 구현하였습니다 

## 집중적인 코드리뷰
아직 완성본이 아니라 validation이 완벽하지 않습니다 
차차  추가할 예정이며 어떤 validation이 추가되면 좋겠다 싶은 부분은 리뷰로 달아주시면 감사하겠습니다! 

## 관련 이슈
- #1 

## 코드리뷰 룰
R(Request Change): 해당 블럭은 꼭 변경해주셨으면 좋겠습니다.
C(Comment): 웬만하면 고려해주시면 좋겠습니다.
A(Approve): 반영해도 좋고 넘어가도 좋습니다. 혹은 사소한 의견입니다.

2023-02-20 01:10 UTC, cloudwi approved these changes

2023-02-20 01:10 UTC, cloudwi commented
고생하셨습니다

2023-02-20 04:29 UTC, Tnfls99 requested changes
예원님, 주영님 고생많으셨습니다!

고민해볼 수 있는 부분이 굉장히 많아보이는데, 깔끔하게 잘 작성해주신 것 같습니다 👍
제가 궁금한 점을 몇가지 적어보았으니 한번 확인부탁드려요 ☺️☀️
혹시 제가 남긴 것에서 궁금한 점이 있다면 얼마든지 편하게 질문해주시기 바랍니다!!

고생하셨습니다 !

2023-02-20 04:29 UTC, Tnfls99 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Period.java
> +
R: 저희 여행 기간을 몇박 몇일로 받기로 한 기억이 나네요!
혹시 제가 놓친 부분이라면 넘어가셔도 될 것 같습니다.
아니라면 시작일과 끝일을 int로 받아도 상관 없을 것 같네요 !

2023-02-20 04:29 UTC, Tnfls99 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private Long totalCost;
R: 가격은 음수가 될 수 없으니 BigInteger, BigDecimal 을 사용하는 것은 어떨까요 ??
돈이나 중요한 값을 다룰때에는 BigDecimal을 많이 사용한다고 하네요 ! [참고 사이트](https://jsonobject.tistory.com/466)

2023-02-20 04:29 UTC, Tnfls99 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private String thumbnail;
C: thumbnail은 Image 객체가 아닌 String 을 사용한 이유가 있을까용 ?

2023-02-20 04:29 UTC, Tnfls99 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	}
A: Country Validation은 다시 하실 예정이라고 들었습니다! 같이 해보면 좋을 것 같아요 ㅎㅎㅎ

2023-02-20 04:29 UTC, Tnfls99 commented on src/test/java/shop/zip/travel/domain/travelog/entity/PeriodTest.java
> +}
C: 이대로 날짜를 받는 것이 유지된다면 오늘 이후의 날짜를 선택할 경우 가능하지 않는 로직을 추가하면 좋을 것 같습니다 !

2023-02-20 04:29 UTC, Tnfls99 commented on src/test/java/shop/zip/travel/domain/travelog/entity/TravelogueTest.java
> +	@DisplayName("존재하지 않는 나라명을 입력할 경우 IllegalArgumentException 을 던진다")
A: 존재하지 않는 나라에 대해 입력이 들어왔을 경우 IllegalArgumentException이 좋을지, 나라명이 잘못 들어왔다는 특정 예외를 주면 좋을지 고민해보면 좋을 것 같아요. 

잘못된 나라가 들어오면 지도 API를 거치지 않은 비정상적인 접근이 발생했다는 것과도 동일한 의미를 가질 것 같습니다.
나중을 위해 비정상정인 접근임을 확인할 수 있는 예외로 처리하는 것이 좋지 않을까하는 제안을 해봅니다!

혹시 이해가 되지 않는다면 편하게 질문해주세요 :)

2023-02-20 07:16 UTC, yewon9609 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private String thumbnail;
앗 그렇네요..! 수정하겠습니다 ☺️

2023-02-20 07:21 UTC, Albatross3 approved these changes
1. content 안에서 image url 을 어떻게 받아낼 수 있을지에 대한 고민
2. 방문한 도시나 랜드마크등을 검색할 때 front 쪽에서 장소 관련 Api를 사용하도록 권해보는 것이 좋을 것 같아요

2023-02-20 07:21 UTC, Albatross3 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private String thumbnail;
R: 현재 SubTranvelLogue 에서 image 들을 가지고 있어서 굳이 없어도 되는 필드인 것 같습니다.
게시물 목록 페이지에서 이미지들을 가져와야 하는데 이때는  TravelLogue id 값을 바탕으로 SubTravelLogue 리스트를 가져오고 그안에서 이미지들을 가져오면 될 것 같습니다

2023-02-20 07:21 UTC, Albatross3 commented on src/main/java/shop/zip/travel/domain/travelog/entity/SubTravelogue.java
> +
R: 나중에 image 를 조회하기 위해서는 List<Image> images 를 가지고 있는 것이 SubTravellogue 객체를 통해 바로 가져올 수 있기 때문에 더 좋아보입니다
즉  Lisst 필드가 필요해 보입니다

2023-02-20 07:21 UTC, Albatross3 commented on src/main/java/shop/zip/travel/domain/travelog/entity/SubTravelogue.java
> +
Travellogue 를 통해 subTravellogue를 조회하기 때문에 순서가 있어야 할 것 같습니다
day라는 필드가 있어야 순서대로 리스트를 나타낼 수 있을 것 같습니다

2023-02-20 07:21 UTC, Albatross3 commented on src/test/java/shop/zip/travel/domain/travelog/entity/TravelogueTest.java
> +	@DisplayName("존재하지 않는 나라명을 입력할 경우 IllegalArgumentException 을 던진다")
저도 동의합니다:) 구체적인 예외를 정해나가면 좋을 것 같습니다

2023-02-20 07:27 UTC, yewon9609 commented on src/test/java/shop/zip/travel/domain/travelog/entity/TravelogueTest.java
> +	@DisplayName("존재하지 않는 나라명을 입력할 경우 IllegalArgumentException 을 던진다")
먼저, 저 IllegalArgumentException을 던졌던 이유는 
Travelogue 엔티티 안에서 Assert로 검증해주기 때문에 IllegalArgumentException 을 던졌습니다..!
(예외 메세지는 "국가명을 확인해주세요" 입니다)

음.. 말씀하신 의도는 이해했습니다..! 
다만, 지도 API를 거치지 않은것을 모두 비정상적인 접근이라고 보는게 맞은가? 라는 생각이 들고 , 
지도 API를 거치지 않더라도 나라이름을 제대로 입력한다면 (말씀하신)비정상적인 접근임을 확인할 수 있는 방법이 없다고 생각이들어요..! 
최선의 방법은 최대한 보안적인 부분은 감추는게 맞다고 생각이 들구요 !

더해서 비즈니스 로직이 더해진 검증이 아닌, 정말 현존하는 나라인지 아닌지를 검증하는 것이기 때문에 커스텀 예외를 던지지 않고 IllegalArgumentException으로 처리하였습니다 🤔

2023-02-20 07:49 UTC, yewon9609 commented on src/main/java/shop/zip/travel/domain/travelog/entity/SubTravelogue.java
> +
앗 그걸 빼먹었네요 추가하겠습니다!

2023-02-20 11:34 UTC, yewon9609 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private String thumbnail;
@Tnfls99 현재 Image가 SubTravelogue와 다대일 연관관계를 맺고있어서 String으로 해줬던 것 같습니다 
thumbnail도 값객체로 포장할지 말지 고민을좀 해봐야 할 것 같아요...! 

@Albatross3 오늘 회의한 결과로 진행하겠습니다 :)

2023-02-20 11:36 UTC, yewon9609 commented on src/main/java/shop/zip/travel/domain/travelog/entity/Travelogue.java
> +	private Long totalCost;
다같이 회의한 결과대로 Long으로 처리하겠습니다 ~!

2023-02-20 12:14 UTC, yewon9609 commented on src/main/java/shop/zip/travel/domain/travelog/entity/SubTravelogue.java
> +
이 생각은 못해봤네요 ~! 감사합니다 :)

2023-02-21 06:59 UTC, yewon9609 commented
@cloudwi @Tnfls99 @Albatross3 
리뷰 반영하였습니다! 확인해주시면 감사하겠습니다 :)

2023-02-21 15:14 UTC, Tnfls99 approved these changes
고생하셨습니다 !!

2023-02-21 15:15 UTC, merged